# Site settings
title: Honors Thesis
email: max@barvian.me
description: > # ignore newlines until "baseurl:"
  A self-help iPhone application for patients with Generalized
  Anxiety Disorder (GAD).
baseurl: '/thesis'
url: "http://barvian.me" # the base hostname & protocol for your site
twitter_username: mbarvian
github_username:  mbarvian

# Conversion
markdown: kramdown
kramdown:
  auto_ids: false
