# Site settings
title: Honors Thesis
email: max@barvian.me
description: >
  A self-help iPhone application for patients with Generalized
  Anxiety Disorder (GAD).
baseurl: /thesis
url: http://barvian.me

# Markdown
markdown: kramdown
kramdown:
  auto_ids: false
